### ISSUE TITLE
Horizontal overflow on the treemap iframe

### ISSUE THREAD

**Issue by gocemitevski** [openspending/subsidystories.eu#10]
When embedded as an iframe the Treemap graph is overflowing horizontally which causes a horizontal scrollbar to appear below the iframe content. The markup of the graph needs to be restructured, to not have the elements wrapped in floating divs.

These updates need to be made:

* Remove the .row class from `<div ng-switch="state.params.visualizations[0]" class="row">`
* Remove the wrapping div around .breadcrumb
* Remove the .col-xs-12 class from .x-visualization-chart

**Comment by akariv** [comment]
@kravets-levko can you please take a look?

**Comment by gocemitevski** [comment]
@kravets-levko here is a screenshot, as well...

![screenshot from 2016-12-26 16-50-22](https://cloud.githubusercontent.com/assets/359855/21483978/7a6d47a0-cb8b-11e6-9e2c-da0e15262f0c.png)

**Comment by kravets-levko** [comment]
@akariv Yes, already on it

**Comment by gocemitevski** [comment]
@kravets-levko are you blocked with this issue?
