### ISSUE TITLE
Add concatenated dataset for download behind the "data" tab

### ISSUE THREAD

**Issue by annafralberts** [openspending/subsidystories.eu#12]
Hey @gocemitevski and @akariv 

Can you add the concatenated dataset - in full (with all columns - not the trimmed down version) to subsidystories.eu so that I can already start sharing this beta-version?

Thanks!

**Comment by akariv** [comment]
You mean the download link for the raw data, right?

**Comment by annafralberts** [comment]
Yes :)

**Comment by gocemitevski** [comment]
@annafralberts we'll be providing raw data per country or for the whole project? What I'm asking is actually do we need to have one download button for the whole site, or one, for each country?

cc @akariv

**Comment by akariv** [comment]
We will have one download button with the entire data.

I'll put in the URL here once I have it.

**Comment by annafralberts** [comment]
Reviving this issue. Can this download button put on the front page, or under the data tab?
