### ISSUE TITLE
Add Disclaimer text in Footer

### ISSUE THREAD

**Issue by annafralberts** [openspending/subsidystories.eu#22]
Add Disclaimer text

**Comment by michaeljokf** [comment]
Please note that large amounts of the data presented were scraped from the web & PDFs, which could have led to errors in the data. Furthermore, there are eight different amount types throughout all of the datasets (see documentation). Make sure you compare to the right amounts. 

This could be the disclaimer.

**Comment by michaeljokf** [comment]
footer didnt make sense due to the layout so I just added two sentences right before you select the countries (the dropdown)
