### ISSUE TITLE
Add links to sub-pages for countries

### ISSUE THREAD

**Issue by annafralberts** [openspending/subsidystories.eu#23]
On the country pages the 
download button should have a download link for that country's dataset
the view details links to the OS-viewer for that country.

**Comment by akariv** [comment]
Link to use:

`https://datastore.openspending.org/6018ab87076187018fc29c94a68a3cd2/CC-eu-esif-funds-beneficiaries-2000-2020-full/data/CC-eu-esif-funds-beneficiaries-2007-2020-full.csv`

Replace 'CC' with country code (in lower case), e.g.:


https://datastore.openspending.org/6018ab87076187018fc29c94a68a3cd2/at-eu-esif-funds-beneficiaries-2000-2020-full/data/at-eu-esif-funds-beneficiaries-2007-2020-full.csv

**Comment by akariv** [comment]
Link to OS-Viewer:

`http://next.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:CC-eu-esif-funds-beneficiaries-2000-2020-full`

(CC is the country code as above)
