### ISSUE TITLE
Angularize the static prototype

### ISSUE THREAD

**Issue by pwalsh** [openspending/subsidystories.eu#3]
# Description

We have a decent set of static HTML mocks for the functionality of this site. We need to get it converted to Angular.

# Tasks

- [ ] @akariv to define

Q for @akariv do we use babbage.ui as a lib to query the OpenSpending API in general, even if we don't use the views from that lib?

**Comment by akariv** [comment]
I think we should use iframes and embed OS-Viewer visualisations based on
the state.
There's actually no acute need to angularise the code, especially if the
main developer feels uncomfortable with using this framework.

**Comment by pwalsh** [comment]
@akariv ok. and there are lots of data points that are not os-viewer based (counts and totals and so forth). Feel free to close this if https://github.com/openspending/subsidystories.eu/issues/2 will be enough to cover the next set of work that @gocemitevski should do
