### ISSUE TITLE
Responsiveness issues

### ISSUE THREAD

**Issue by akariv** [openspending/subsidystories.eu#31]
e.g. Try to open the website in a window 1300px wide, the dropdown disappears and the map is not shown correctly

**Comment by michaeljokf** [comment]
yeah I had what I think are similar problems (using Firefox). The header text and the dropdown were not shown when the browser was at 100% - when zooming out to 80% or lower the entire thing was displayed. 

If the text is too long, let me know, but I assume its on the programming side?
