### ISSUE TITLE
CSV download link broken

### ISSUE THREAD

**Issue by akariv** [openspending/subsidystories.eu#32]
It's currently 
`https://datastore.openspending.org/6018ab87076187018fc29c94a68a3cd2/DE-eu-esif-funds-beneficiaries-2000-2020-full/data/DE-eu-esif-funds-beneficiaries-2007-2020-full.csv`

it should be
`http://datastore.openspending.org/6018ab87076187018fc29c94a68a3cd2/de-eu-esif-funds-beneficiaries-2000-2020-full/data/DE-eu-esif-funds-beneficiaries-2007-2020-full.csv`

https->http, lowercase country code.

**Comment by akariv** [comment]
Also OS-Viewer link should have the country code in lower case.

**Comment by kravets-levko** [comment]
Fixed, but there is S3 error:
```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>1AE492DD0C533D8A</RequestId>
  <HostId>
    ETxgSghrCxUjYEQTsh3SIr0TiE85c99Detx1tUqNnMrGViHUS8zB4DOxuD1qEnZ64Crbno/HO+k=
  </HostId>
</Error>
```
[Example](http://datastore.openspending.org/6018ab87076187018fc29c94a68a3cd2/pl-eu-esif-funds-beneficiaries-2000-2020-full/data/PL-eu-esif-funds-beneficiaries-2007-2020-full.csv) CSV (for Poland)

**Comment by akariv** [comment]
What's the link you're using?

**Comment by kravets-levko** [comment]
For example this: http://datastore.openspending.org/6018ab87076187018fc29c94a68a3cd2/pl-eu-esif-funds-beneficiaries-2000-2020-full/data/PL-eu-esif-funds-beneficiaries-2007-2020-full.csv
But it does not matter - the same error is (I suppose) for every country - I tried Germany, Austria, Poland and some others - all with the same error.

**Comment by akariv** [comment]
There's still an upper case bit there...
All instances of PL need to be lower case

**Comment by kravets-levko** [comment]
yes, you're right, thank you!
