### ISSUE TITLE
Deploy app to Heroku

### ISSUE THREAD

**Issue by akariv** [openspending/subsidystories.eu#4]
We need to provide simple password protection to the site.

Levko - we can use the same solution that we used for the Ebola Tracker.

Domain should be subsidystories.eu - I'll provide details about that later.

**Comment by kravets-levko** [comment]
If you don't mind - I'll implement it a bit simpler - as a HTTP Basic Auth - this will allow to implement auth with a minimum amount of code.

**Comment by akariv** [comment]
Even better. I don't really know what you did in the Ebola Tracker, so I
simply assumed that it was basic auth ;)

**Comment by kravets-levko** [comment]
It was my first app in node - do not judge strictly :wink:
I've added there a separate page for auth, with a simple session in cookies. A bit complicated...
