### ISSUE TITLE
Billions - > Billion and Millions -> Million

### ISSUE THREAD

**Issue by annafralberts** [openspending/subsidystories.eu#40]
We just noticed that on the country pages everywhere it says 
X Billions. This shoud be X Billion, without the S
The same for Millions -> Million

**Comment by kravets-levko** [comment]
@annafralberts (cc @michaeljokf) I fixed it for SubsidyStories; but visualizations are embedded from OS Viewer, so there all labels will be with `-s` endings (I can fix it too, but I cannot deploy OS applications, sorry)

**Comment by annafralberts** [comment]
Good for the launch. Thanks!

Op 6 mrt. 2017 21:07 schreef "Levko Kravets" <notifications@github.com>:
