### ISSUE TITLE
OS Viewer should link to country filter PLUS recipient

### ISSUE THREAD

**Issue by annafralberts** [openspending/subsidystories.eu#42]
When you click on "View Details" you see this: http://next.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:at-eu-esif-funds-beneficiaries-2000-2020-full?measure=%22amount.sum%22&groups%5B%5D=%22recipient_beneficiary_name.beneficiary_name%22&filters%5Bgeo_source_beneficiary_country.beneficiary_country_code%5D%5B%5D=%22AT%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en

But it should be filtered for recipients:

http://next.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:at-eu-esif-funds-beneficiaries-2000-2020-full?measure=%22amount.sum%22&groups%5B%5D=%22recipient_beneficiary_id.beneficiary_id%22&filters%5Bgeo_source_beneficiary_country.beneficiary_country_code%5D%5B%5D=%22AT%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en

Otherwise it does not display data. This is the example for Austria, but it goes for all view details.

**Comment by michaeljokf** [comment]
yes so basically add the filter for recipients in the viewer, so that the data is directly displayed.
