### ISSUE TITLE
include Piwik

### ISSUE THREAD

**Issue by michaeljokf** [openspending/subsidystories.eu#47]
Hey @kravets-levko could you pretty pretty please include piwik (or something like that) on the website? 
So that we have some kind of a tracker for the visits on the page?
Maybe you have already included something like this? Thank you very much!

**Comment by kravets-levko** [comment]
@michaeljokf Can you provide me a Piwik or Google Analytics (or any other) snippet? I have no access to any tracker used for our projects.

**Comment by annafralberts** [comment]
Our @knutator will send add it with a PR :)

**Comment by annafralberts** [comment]
<script type="text/javascript">
 var _paq = _paq || [];
 // tracker methods like "setCustomDimension" should be called before "trackPageView"
 _paq.push(['trackPageView']);
 _paq.push(['enableLinkTracking']);
 (function() {
   var u="//traffic.okfn.de/";
   _paq.push(['setTrackerUrl', u+'piwik.php']);
   _paq.push(['setSiteId', '32']);
   var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
   g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
 })();
</script>

**Comment by annafralberts** [comment]
@kravets-levko our developer knut said this should work - this is based on our OKF Germany Piwik :)

**Comment by kravets-levko** [comment]
Yes, at least it sends something to Piwik server. Will create PR in a couple of minutes
