### ISSUE TITLE
include OKI and OKF Germany logos

### ISSUE THREAD

**Issue by michaeljokf** [openspending/subsidystories.eu#52]
@kravets-levko as we discussed. The footer should be adjusted a little. Both the Adessium and the Open Budgets EU logos should be adjusted (shrunken) so that the OKI and OKF Germany logos can be included. 

You can find the Open Knowledge International logos here: https://okfn.org/about/resources/
I would suggest using the green version, that would go well with the black one that we have from Open Knowledge Germany (below). 

![logo_black](https://cloud.githubusercontent.com/assets/22743376/23700308/b56ab6ea-03f2-11e7-8d46-a7254b23395c.png)

**Comment by kravets-levko** [comment]
@michaeljokf Ready and deployed

**Comment by michaeljokf** [comment]
thanks @kravets-levko it looks really good!
